INSERT INTO interest (`interest_id`, `interest`) VALUES (1, "Technology");
INSERT INTO interest (`interest_id`, `interest`) VALUES (2, "Science");
INSERT INTO interest (`interest_id`, `interest`) VALUES (3, "Health");
INSERT INTO interest (`interest_id`, `interest`) VALUES (4, "Education");
INSERT INTO interest (`interest_id`, `interest`) VALUES (5, "Art");
INSERT INTO interest (`interest_id`, `interest`) VALUES (6, "Design");
INSERT INTO interest (`interest_id`, `interest`) VALUES (7, "Entertainment");
INSERT INTO interest (`interest_id`, `interest`) VALUES (8, "Sports");
INSERT INTO interest (`interest_id`, `interest`) VALUES (9, "Travel");
INSERT INTO interest (`interest_id`, `interest`) VALUES (10, "Business ");
INSERT INTO interest (`interest_id`, `interest`) VALUES (11, "Food ");
INSERT INTO interest (`interest_id`, `interest`) VALUES (12, "Politics");
INSERT INTO interest (`interest_id`, `interest`) VALUES (13, "Career ");
INSERT INTO interest (`interest_id`, `interest`) VALUES (14, "DIY ");
INSERT INTO interest (`interest_id`, `interest`) VALUES (15, "Fashion ");
INSERT INTO interest (`interest_id`, `interest`) VALUES (16, "Automotive");
INSERT INTO interest (`interest_id`, `interest`) VALUES (17, "Photograph");
INSERT INTO interest (`interest_id`, `interest`) VALUES (18, "Lifestyle");
INSERT INTO interest (`interest_id`, `interest`) VALUES (19, "Fitness ");
INSERT INTO interest (`interest_id`, `interest`) VALUES (20, "Adventure ");
