INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (1, "Artificial Intelligence", 1);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (2, "Software Development", 1);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (3, "Cybersecurity", 1);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (4, "Gadgets", 1);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (5, "Blockchain", 1);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (6, "Physics", 2);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (7, "Chemistry", 2);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (8, "Biology", 2);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (9, "Astronomy", 2);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (10, "Fitness", 3);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (11, "Nutrition", 3);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (12, "Mental Health", 3);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (13, "Medical Advancements", 3);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (14, "Tutorials", 4);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (15, "Online Courses", 4);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (16, "Study Groups", 4);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (17, "Workshops", 4);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (18, "Painting", 5);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (19, "Sculpture", 5);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (20, "Calligraphy", 5);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (21, "Graphic Design", 6);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (22, "Interior Design", 6);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (23, "UI/UX", 6);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (24, "Movies", 7);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (25, "Music", 7);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (26, "Gaming", 7);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (27, "TV Shows", 7);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (28, "Football", 8);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (29, "Basketball", 8);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (30, "Tennis", 8);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (31, "Esports", 8);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (32, "Destinations", 9);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (33, "Adventure", 9);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (34, "Backpacking", 9);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (35, "Cultural Exploration", 9);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (36, "Entrepreneurship", 10);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (37, "Marketing", 10);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (38, "Finance", 10);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (39, "Recipes", 11);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (40, "Restaurant Reviews", 11);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (41, "Cooking Tips", 11);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (42, "Elections", 12);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (43, "Policy Discussions", 12);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (44, "Diplomacy", 12);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (45, "Job Hunting", 13);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (46, "Networking", 13);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (47, "Skill Development", 13);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (48, "Crafts", 14);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (49, "Home Projects", 14);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (50, "Tech Projects", 14);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (51, "Trends", 15);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (52, "Styling", 15);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (53, "Skincare", 15);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (54, "Cars", 16);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (55, "Motorcycles", 16);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (56, "Electric Vehicles", 16);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (57, "Portrait Photography", 17);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (58, "Nature Photography", 17);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (59, "Street Photography", 17);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (60, "Minimalism", 18);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (61, "Personal Growth", 18);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (62, "Work-Life Balance", 18);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (63, "Home Workouts", 19);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (64, "Weightlifting", 19);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (65, "Running", 19);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (66, "Hiking", 20);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (67, "Camping", 20);
INSERT INTO tags (`tag_id`, `tag`, `interest_id`) VALUES (68, "Rock Climbing", 20);
