INSERT INTO community (`community_id`, `title`, `description`, `cover_photo`, `interest_id`) VALUES (1, "Tech Enthusiasts", "Explore and discuss the latest in technology and innovation", "dummy_image_1.jpg", 1),
(2, "Future of AI", "Dive into the world of artificial intelligence and its impact on society", "dummy_image_2.jpg", 1),
(3, "Science Buffs", "A place to share and discuss groundbreaking scientific discoveries", "dummy_image_3.jpg", 2),
(4, "Health and Wellness", "Discuss topics on physical and mental health for a better lifestyle", "dummy_image_4.jpg", 3),
(5, "Modern Educators", "Innovative teaching methods and education system discussions", "dummy_image_5.jpg", 4),
(6, "Art Lovers", "Explore creativity and share artistic endeavors", "dummy_image_6.jpg", 5),
(7, "Graphic Designers Hub", "Connect and share insights on graphic design and trends", "dummy_image_7.jpg", 6),
(8, "Cinema Fans", "Discuss movies", " TV shows", " and everything entertainment", "dummy_image_8.jpg", 7),
(9, "Sports Arena", "The ultimate hangout for sports fans of all kinds", "dummy_image_9.jpg", 8),
(10, "Travel Addicts", "Share your travel adventures and dream destinations", "dummy_image_10.jpg", 9),
(11, "Startup Founders", "Support and discuss business ideas and strategies", "dummy_image_11.jpg", 10),
(12, "Foodies Unite", "Share your favorite recipes and food experiences", "dummy_image_12.jpg", 11),
(13, "Political Insights", "Debate and analyze the latest political trends", "dummy_image_13.jpg", 12),
(14, "Career Builders", "Find support and tips for career advancement and opportunities", "dummy_image_14.jpg", 13),
(15, "DIY Creators", "Showcase your DIY projects and exchange ideas", "dummy_image_15.jpg", 14),
(16, "Style Trends", "Keep up with the latest in fashion and style", "dummy_image_16.jpg", 15),
(17, "Car Enthusiasts", "Talk about cars", " bikes", " and the latest in the automotive world", "dummy_image_17.jpg", 16),
(18, "Shutterbugs", "Discuss photography tips and share your best shots", "dummy_image_18.jpg", 17),
(19, "Lifestyle Gurus", "Talk about minimalism", " organization", " and lifestyle improvements", "dummy_image_19.jpg", 18),
(20, "Fitness Freaks", "Share your workout routines and fitness journeys", "dummy_image_20.jpg", 19),
(21, "Adventurers Club", "Plan and share thrilling adventure stories and experiences", "dummy_image_21.jpg", 20),
(22, "Tech Startups", "Learn about new and emerging startups in the tech world", "dummy_image_22.jpg", 1),
(23, "Quantum Physics", "Explore the fascinating world of quantum mechanics", "dummy_image_23.jpg", 2),
(24, "Mental Health Matters", "Discuss mental health awareness and support", "dummy_image_24.jpg", 3),
(25, "Learning Innovators", "Ideas for revolutionizing the education space", "dummy_image_25.jpg", 4),
(26, "Digital Artists", "Share your digital creations and get inspired", "dummy_image_26.jpg", 5),
(27, "UI/UX Designers", "Discuss design thinking and create exceptional user experiences", "dummy_image_27.jpg", 6),
(28, "Series Bingers", "Talk about the latest binge-worthy series", "dummy_image_28.jpg", 7),
(29, "Cricket Fans", "Discuss matches", " teams", " and players in cricket", "dummy_image_29.jpg", 8),
(30, "Backpackers Unite", "Connect with solo travelers and group adventurers", "dummy_image_30.jpg", 9),
(31, "Entrepreneur Circle", "Network with budding entrepreneurs and share insights", "dummy_image_31.jpg", 10),
(32, "Vegan Recipes", "Share plant-based food ideas and recipes", "dummy_image_32.jpg", 11),
(33, "World Politics Forum", "Analyze and share views on global politics", "dummy_image_33.jpg", 12),
(34, "Job Seekers", "Find tips", " tricks", " and connections for your next job", "dummy_image_34.jpg", 13),
(35, "DIY Woodworkers", "Share your woodworking projects and tips", "dummy_image_35.jpg", 14),
(36, "Runway Fashionistas", "Discuss fashion weeks", " trends", " and designers", "dummy_image_36.jpg", 15),
(37, "Offroaders Club", "For fans of off-road vehicles and rugged terrains", "dummy_image_37.jpg", 16),
(38, "Portrait Masters", "Tips and tricks for mastering portrait photography", "dummy_image_38.jpg", 17),
(39, "Home Makeovers", "Discuss home decor and organization tips", "dummy_image_39.jpg", 18),
(40, "Weightlifters Guild", "Share your weightlifting tips and personal records", "dummy_image_40.jpg", 19),
(41, "Mountaineers Club", "Stories from the highest peaks and treacherous climbs", "dummy_image_41.jpg", 20),
(42, "IoT Innovators", "Explore the future of smart devices and IoT", "dummy_image_42.jpg", 1),
(43, "Space Explorers", "Discuss space exploration and astronomical events", "dummy_image_43.jpg", 2),
(44, "Yoga and Meditation", "Discuss techniques and benefits of yoga and mindfulness", "dummy_image_44.jpg", 3),
(45, "Online Educators", "Connect with educators creating online courses", "dummy_image_45.jpg", 4),
(46, "Street Artists", "Discover the vibrant world of street art and graffiti", "dummy_image_46.jpg", 5),
(47, "Interior Designers Hub", "Exchange interior design ideas and projects", "dummy_image_47.jpg", 6),
(48, "Anime Lovers", "Talk about your favorite anime and manga", "dummy_image_48.jpg", 7),
(49, "Football Fans", "Connect with fellow football enthusiasts", "dummy_image_49.jpg", 8),
(50, "Cultural Travelers", "Discover and discuss cultural tourism", "dummy_image_50.jpg", 9),
(51, "Cloud Computing Trends", "Discuss the latest innovations in cloud technology", "dummy_image_51.jpg", 1),
(52, "Astrophysics Enthusiasts", "Explore the mysteries of the universe and black holes", "dummy_image_52.jpg", 2),
(53, "Holistic Healing", "Discuss natural remedies and holistic wellness practices", "dummy_image_53.jpg", 3),
(54, "Teachers' Lounge", "Share experiences and strategies for impactful teaching", "dummy_image_54.jpg", 4),
(55, "Sculptors Guild", "Discuss sculpture techniques and showcase your creations", "dummy_image_55.jpg", 5),
(56, "Web Designers Hub", "Learn and share modern web design techniques", "dummy_image_56.jpg", 6),
(57, "Comedy Lovers", "Share and laugh at your favorite comedy shows and memes", "dummy_image_57.jpg", 7),
(58, "Basketball Fans", "Talk about your favorite teams", " players", " and leagues", "dummy_image_58.jpg", 8),
(59, "Luxury Travelers", "Explore destinations known for their exclusivity and charm", "dummy_image_59.jpg", 9),
(60, "Stock Market Insights", "Analyze and share investment strategies and stock trends", "dummy_image_60.jpg", 10),
(61, "Food Truck Fans", "Discover and discuss the best street food and food trucks", "dummy_image_61.jpg", 11),
(62, "Policy Makers", "Debate and propose ideas for impactful policies", "dummy_image_62.jpg", 12),
(63, "Job Interview Tips", "Share advice and experiences to ace interviews", "dummy_image_63.jpg", 13),
(64, "DIY Electronics", "Build and share cool electronics and IoT projects", "dummy_image_64.jpg", 14),
(65, "Boho Chic Community", "Explore bohemian fashion and its cultural inspirations", "dummy_image_65.jpg", 15),
(66, "Supercar Fans", "Admire and discuss the world of luxury and performance cars", "dummy_image_66.jpg", 16),
(67, "Wildlife Photography", "Share and learn tips for capturing the beauty of nature", "dummy_image_67.jpg", 17),
(68, "Work-Life Balance", "Discuss strategies to balance career and personal life", "dummy_image_68.jpg", 18),
(69, "Calisthenics Warriors", "Explore bodyweight exercises and fitness techniques", "dummy_image_69.jpg", 19),
(70, "Extreme Sports Club", "For fans of skydiving", " surfing", " and other extreme adventures", "dummy_image_70.jpg", 20),
(71, "Blockchain Innovators", "Explore blockchain technologies and cryptocurrency trends", "dummy_image_71.jpg", 1),
(72, "Meteorology Lovers", "Discuss weather patterns", " forecasts", " and climate change", "dummy_image_72.jpg", 2),
(73, "Healthy Recipes", "Share recipes focused on nutritious and wholesome meals", "dummy_image_73.jpg", 3),
(74, "Virtual Classrooms", "Ideas for enhancing online education experiences", "dummy_image_74.jpg", 4),
(75, "Abstract Art Explorers", "Discuss abstract art and its philosophical inspirations", "dummy_image_75.jpg", 5);