INSERT INTO feedback (`feedback_id`, `feedback`) VALUES (1, "Spam Content"),
(2, "Offensive Language"),
(3, "Hate Speech"),
(4, "Harassment"),
(5, "Misinformation"),
(6, "Violent or Graphic Content"),
(7, "Scams or Fraudulent Content"),
(8, "Privacy Violations"),
(9, "Inappropriate for the Community"),
(10, "Plagiarized Content"),
(11, "Sexually Explicit Content"),
(12, "Self-Harm Promotion"),
(13, "Clickbait"),
(14, "Overly Aggressive Debates"),
(15, "Unwanted Advertisements");